FROM golang:1.18.2-alpine as dev

WORKDIR /work

FROM golang:1.18.2-alpine as build

WORKDIR /videos
COPY ./* /videos/
RUN go build -o videos

FROM alpine as runtime
COPY --from=build /videos /usr/local/bin/videos
COPY ./videos.json /
COPY run.sh /
RUN chmod +x run.sh
ENTRYPOINT ["./run.sh"]
